# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-11 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='db',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
