# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-11 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20200311_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
